name: cse-153-assignment2
channels:
    - conda-forge
    - defaults
dependencies:
    - _openmp_mutex=4.5
    - anyio=4.7.0
    - argon2-cffi=21.3.0
    - argon2-cffi-bindings=21.2.0
    - asttokens=3.0.0
    - async-lru=2.0.4
    - babel=2.16.0
    - beautifulsoup4=4.12.3
    - bleach=6.2.0
    - brotli=1.1.0
    - brotli-bin=1.1.0
    - brotli-python=1.0.9
    - bzip2=1.0.8
    - ca-certificates=2025.4.26
    - cairo=1.18.4
    - certifi=2025.4.26
    - cffi=1.17.1
    - charset-normalizer=3.3.2
    - colorama=0.4.6
    - comm=0.2.1
    - contourpy=1.3.2
    - cycler=0.12.1
    - debugpy=1.8.11
    - decorator=5.1.1
    - defusedxml=0.7.1
    - double-conversion=3.3.1
    - executing=0.8.3
    - font-ttf-dejavu-sans-mono=2.37
    - font-ttf-inconsolata=3.000
    - font-ttf-source-code-pro=2.038
    - font-ttf-ubuntu=0.83
    - fontconfig=2.15.0
    - fonts-conda-ecosystem=1
    - fonts-conda-forge=1
    - fonttools=4.58.1
    - freetype=2.13.3
    - glib=2.84.2
    - glib-tools=2.84.2
    - graphite2=1.3.13
    - gst-plugins-base=1.24.11
    - gstreamer=1.24.11
    - h11=0.16.0
    - harfbuzz=11.2.1
    - httpcore=1.0.9
    - httpx=0.28.1
    - icu=75.1
    - intel-openmp=2024.2.1
    - ipykernel=6.29.5
    - ipython=9.1.0
    - ipython_pygments_lexers=1.1.1
    - jedi=0.19.2
    - joblib=1.5.1
    - json5=0.9.25
    - jsonschema=4.23.0
    - jsonschema-specifications=2023.7.1
    - jupyter-lsp=2.2.5
    - jupyter_client=8.6.3
    - jupyter_core=5.7.2
    - jupyter_events=0.12.0
    - jupyter_server=2.15.0
    - jupyter_server_terminals=0.5.3
    - jupyterlab=4.3.4
    - jupyterlab_pygments=0.3.0
    - jupyterlab_server=2.27.3
    - kiwisolver=1.4.8
    - krb5=1.21.3
    - lcms2=2.17
    - lerc=4.0.0
    - libblas=3.9.0
    - libbrotlicommon=1.1.0
    - libbrotlidec=1.1.0
    - libbrotlienc=1.1.0
    - libcblas=3.9.0
    - libclang13=20.1.6
    - libdeflate=1.24
    - libexpat=2.7.0
    - libffi=3.4.6
    - libfreetype=2.13.3
    - libfreetype6=2.13.3
    - libgcc=15.1.0
    - libglib=2.84.2
    - libgomp=15.1.0
    - libhwloc=2.11.2
    - libiconv=1.18
    - libintl=0.22.5
    - libintl-devel=0.22.5
    - libjpeg-turbo=3.1.0
    - liblapack=3.9.0
    - liblzma=5.8.1
    - libogg=1.3.5
    - libpng=1.6.47
    - libsodium=1.0.18
    - libsqlite=3.50.0
    - libtiff=4.7.0
    - libvorbis=1.3.7
    - libwebp-base=1.5.0
    - libwinpthread=12.0.0.r4.gg4f2fc60ca
    - libxcb=1.17.0
    - libxml2=2.13.8
    - libxslt=1.1.39
    - libzlib=1.3.1
    - llvm-openmp=20.1.6
    - matplotlib=3.10.3
    - matplotlib-base=3.10.3
    - matplotlib-inline=0.1.6
    - mido=1.2.10
    - mistune=3.1.2
    - mkl=2024.2.2
    - munkres=1.1.4
    - nbclient=0.10.2
    - nbconvert-core=7.16.6
    - nbformat=5.10.4
    - nest-asyncio=1.6.0
    - notebook=7.3.2
    - notebook-shim=0.2.4
    - numpy=2.2.6
    - openjpeg=2.5.3
    - openssl=3.5.0
    - overrides=7.4.0
    - packaging=25.0
    - pandas=2.2.3
    - pandocfilters=1.5.0
    - parso=0.8.4
    - patsy=1.0.1
    - pcre2=10.45
    - pillow=11.2.1
    - pip=25.1.1
    - pixman=0.46.0
    - platformdirs=4.3.7
    - ply=3.11
    - prometheus_client=0.21.1
    - prompt-toolkit=3.0.43
    - prompt_toolkit=3.0.43
    - psutil=5.9.0
    - pthread-stubs=0.4
    - pure_eval=0.2.2
    - pycparser=2.21
    - pygments=2.19.1
    - pyparsing=3.2.3
    - pyqt=5.15.10
    - pyqt5-sip=12.13.0
    - pyside6=6.9.0
    - pysocks=1.7.1
    - python=3.12.10
    - python-dateutil=2.9.0.post0
    - python-fastjsonschema=2.20.0
    - python-json-logger=3.2.1
    - python-tzdata=2025.2
    - python_abi=3.12
    - pytz=2025.2
    - pywin32=308
    - pywinpty=2.0.15
    - pyyaml=6.0.2
    - pyzmq=26.2.0
    - qhull=2020.2
    - qt-main=5.15.15
    - qt6-main=6.9.0
    - referencing=0.30.2
    - requests=2.32.3
    - rfc3339-validator=0.1.4
    - rfc3986-validator=0.1.1
    - rpds-py=0.22.3
    - scikit-learn=1.6.1
    - scipy=1.15.2
    - seaborn=0.13.2
    - seaborn-base=0.13.2
    - send2trash=1.8.2
    - setuptools=80.9.0
    - sip=6.7.12
    - six=1.17.0
    - sniffio=1.3.0
    - soupsieve=2.5
    - stack_data=0.2.0
    - statsmodels=0.14.4
    - tbb=2021.13.0
    - terminado=0.17.1
    - threadpoolctl=3.6.0
    - tinycss2=1.4.0
    - tk=8.6.13
    - tornado=6.5.1
    - traitlets=5.14.3
    - typing-extensions=4.12.2
    - typing_extensions=4.12.2
    - tzdata=2025b
    - ucrt=10.0.22621.0
    - unicodedata2=16.0.0
    - urllib3=2.3.0
    - vc=14.3
    - vc14_runtime=14.42.34438
    - vs2015_runtime=14.42.34438
    - wcwidth=0.2.5
    - webencodings=0.5.1
    - websocket-client=1.8.0
    - wheel=0.45.1
    - win_inet_pton=1.1.0
    - winpty=0.4.3
    - xorg-libxau=1.0.12
    - xorg-libxdmcp=1.1.5
    - yaml=0.2.5
    - zeromq=4.3.5
    - zstd=1.5.7
    - pip:
          - absl-py==2.3.0
          - aiohappyeyeballs==2.6.1
          - aiohttp==3.12.7
          - aiosignal==1.3.2
          - attrs==25.3.0
          - filelock==3.13.1
          - frozenlist==1.6.0
          - fsspec==2024.6.1
          - grpcio==1.72.1
          - idna==3.10
          - jinja2==3.1.4
          - lightning-utilities==0.14.3
          - markdown==3.8
          - markupsafe==2.1.5
          - mpmath==1.3.0
          - multidict==6.4.4
          - networkx==3.3
          - pretty-midi==0.2.10
          - propcache==0.3.1
          - protobuf==6.31.1
          - pybind11==2.13.6
          - pytorch-lightning==2.5.1.post0
          - sympy==1.13.3
          - tensorboard==2.19.0
          - tensorboard-data-server==0.7.2
          - tensorboardx==2.6.2.2
          - torch==2.7.0+cu118
          - torchaudio==2.7.0+cu118
          - torchmetrics==1.7.2
          - torchvision==0.22.0+cu118
          - tqdm==4.67.1
          - werkzeug==3.1.3
          - yarl==1.20.0
